/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hy_serialportdemo_device_DeviceSerialPort */

#ifndef _Included_com_frey_serialportdemo_device_DeviceSerialPort
#define _Included_com_frey_serialportdemo_device_DeviceSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hy_serialportdemo_device_DeviceSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_frey_serialportdemo_device_DeviceSerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_hy_serialportdemo_device_DeviceSerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_frey_serialportdemo_device_DeviceSerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
